services:
  tabla:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabla.rule=Host(`tabla.nuc.home`)"
      - "traefik.http.routers.tabla.entrypoints=http"
      - "traefik.http.services.tabla.loadbalancer.server.port=80"
    networks:
      - shared-services

networks:
  shared-services:
    external: true
